label.titulo.pagina.consulta = Agendas Cadastradas
label.titulo.pagina.cadastro = Cadastro de Agenda
label.periodo.disponivel = Periodo Disponivel
label.modal.titulo = Confirmacao de Exclusao
label.modal.corpo = Deseja realizar a Exclusao da agenda?
