label.titulo.pagina.consulta = Compromissos Cadastrados
label.titulo.pagina.cadastro = Cadastro de Compromisso
label.funcionario = Funcionario
label.agenda = Agenda
label.data = Data
label.horario = Horario
label.modal.titulo = Confirmacao de Exclusao
label.modal.corpo = Deseja realizar a Exclusao do compromisso?
