label.titulo.pagina.consulta = Relatorio de Compromissos
label.data.inicial = Data Inicial
label.data.final = Data Final
label.gerar = Gerar Relatorio
label.funcionario = Funcionario
label.agenda = Agenda
label.data = Data
label.horario = Horario
